apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
  namespace: hello-namespace  # Specify the namespace here
spec:
  selector:
    app: hello-node
  ports:
    - protocol: TCP
      port: 3088
      targetPort: 3099  # Make sure this matches the port your app listens on
  type: LoadBalancer  # Use NodePort if LoadBalancer isn’t available locally
